[mongodb]
mongodb.deepthi.cloud

[redis]
redis.deepthi.cloud

[mysql]
mysql.deepthi.cloud

[rabbitmq]
rabbitmq.deepthi.cloud

[cart]
172.31.28.98

[local]
localhost


[all:vars]
ansible_user=ec2-user 
ansible_password=DevOps321

