- name: setup shipping server
  hosts: shipping
  become: true
  tasks: 
  - name: install maven
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: present
    loop:
    - maven
    - mysql 
      
  - name: add system user roboshop
    ansible.builtin.user:
      name: roboshop
      comment: roboshop system user
      shell: /sbin/nologin
      home: /app 
      system: true

  - name: remove app directory  
    ansible.builtin.file:
      path: /app
      state: absent    

  - name: setup app directory  
    ansible.builtin.file:
      path: /app
      state: directory 
     
  - name: remove shipping file
    ansible.builtin.file:
      path: /tmp/shipping.zip
      state: absent 

  - name: Download the application code to created app directory.
    ansible.builtin.get_url: 
      url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip 
      dest: /tmp/shipping.zip

  - name: unzip shipping file  
    ansible.builtin.unarchive:
      src: /tmp/shipping.zip
      dest: /app
      remote_src: yes 

  - name: install dependencies
    ansible.builtin.command: mvn clean package
    args:
      chdir: /app

  - name: move jar file
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar 
    args:
      chdir: /app
  
  - name: setup shipping service 
    ansible.builtin.copy:
      src: shipping.service
      dest: /etc/systemd/system/shipping.service

  - name: Install PyMySQL
    ansible.builtin.pip: 
      name: PyMySQL
      state: present

  - name: Import database dump
    community.mysql.mysql_db:
      name: all
      state: import
      target: "{{ item }}"
      login_host: mysql.deepthi.cloud
      login_user: root
      login_password: RoboShop@1
    loop:
    - /app/db/schema.sql
    - /app/db/app-user.sql 
    - /app/db/master-data.sql


  - name: reload systemd daemons
    ansible.builtin.systemd:
      daemon_reload: yes

  - name: enable and start shipping
    ansible.builtin.service:
      name: shipping
      state: restarted
      enabled: yes    
      

      

  

